name: "Full-stack tests"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "50 3/6 * * *"

defaults:
  run:
    shell: bash -leo pipefail {0} {0}

jobs:
  test:
    name: OS=${{ matrix.os }}, Python=${{ matrix.python-version }}, Variant=${{ matrix.variant }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
        python-version:
          - "3.12"
          - "3.13"
        variant:
          - "development"
          - "released"

    env:
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt
      PYTEST_ARGS: -vx -n logical --rootdir=. --durations=20

    steps:
    - uses: actions/checkout@v7

    # Each of these checkouts can be done on a feature branch
    # https://github.com/actions/checkout#checkout-a-different-branch

    # Only check out the repos whose tests directly run; development
    # installs of other packages are brought in via pip via micromamba
    - name: Checkout OpenFF NAGL
      if: matrix.variant == 'development'
      uses: actions/checkout@v7
      with:
        repository: openforcefield/openff-nagl
        path: openff-nagl

    - name: Checkout Interchange
      if: matrix.variant == 'development'
      uses: actions/checkout@v7
      with:
        repository: openforcefield/openff-interchange
        path: openff-interchange

    - name: Checkout OpenFF Fragmenter
      if: matrix.variant == 'development'
      uses: actions/checkout@v7
      with:
        repository: openforcefield/openff-fragmenter
        path: openff-fragmenter

    - name: Checkout OpenFF Units
      if: matrix.variant == 'development'
      uses: actions/checkout@v7
      with:
        repository: openforcefield/openff-units
        path: openff-units

    - name: Checkout OpenFF Utilities
      if: matrix.variant == 'development'
      uses: actions/checkout@v7
      with:
        repository: openforcefield/openff-utilities
        path: openff-utilities

    - name: Set up conda environment
      uses: mamba-org/setup-micromamba@v3
      with:
        environment-file: devtools/conda-envs/full-stack.yaml
        create-args: python=${{ matrix.python-version }}

    - name: Make oe_license.txt file from GH org secret "OE_LICENSE"
      env:
        OE_LICENSE_TEXT: ${{ secrets.OE_LICENSE }}
      run: echo "${OE_LICENSE_TEXT}" > ${OE_LICENSE}

    - name: Install most recent development versions
      if: matrix.variant == 'development'
      run: |
        uv pip install --no-deps -e \
          openff-nagl/ \
          openff-interchange/ \
          openff-interchange/plugins/ \
          openff-units/ \
          openff-units/downstream_dummy/ \
          openff-fragmenter/ \
          openff-utilities/
        uv pip list

    - name: Run 'everything all at once' tests of development versions
      run: |
        python -m pytest $PYTEST_ARGS . \
          --ignore=openff-utilities/openff/utilities/_tests/test_provenance.py \

    - name: Run 'everything all at once' tests of releases
      run: |
        python -m pytest --pyargs --lf \
          openff.toolkit --deselect _tests/test_parameter_plugins.py \
          openff.units \
          openff.utilities \
          openff.interchange \
          openff.fragmenter \
          openff.nagl
