name: "Full-stack tests"

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]

    env:
      CI_OS: ${{ matrix.os }}
      PYVER: ${{ matrix.python-version }}
      COV: --cov=openff/units --cov-report=xml --cov-config=setup.cfg --cov-append

    steps:
    - uses: actions/checkout@v3

    # Each of these checkouts can be done on a feature branch
    # https://github.com/actions/checkout#checkout-a-different-branch

    - name: Checkout OpenFF Toolkit
      uses: actions/checkout@v3
      with:
        repository: openforcefield/openff-toolkit
        path: openff-toolkit

    - name: Checkout OpenFF Evaluator
      uses: actions/checkout@v3
      with:
        repository: openforcefield/openff-evaluator
        path: openff-evaluator

    - name: Checkout OpenFF Interchange
      uses: actions/checkout@v3
      with:
        repository: openforcefield/openff-interchange
        path: openff-interchange

    - name: Look around
      run: |
        pwd
        ls -a
        ls openff-*/

    - uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: devtools/conda-envs/full.yaml
        channel-priority: "flexible"
        extra-specs: |
          python=${{ matrix.python-version }}

    - name: Install most recent development versions
      shell: bash -l {0}
      run: |
        conda remove --force openff-interchange -y
        conda remove --force openff-evaluator -y
        conda remove --force openff-toolkit -y

        pip install -e \
          openff-toolkit/ \
          openff-toolkit/utilities/test_plugins/ \
          openffopenff-evaluator/ \
          openff-interchange/ \
          openff-interchange/plugins/

    - name: Run 'everything all at once' tests
      shell: bash -l {0}
      run: |
        python -m pytest openff-*/
